Improved publish action

diff --git a/.github/workflows/publish-and-tag.yml b/.github/workflows/publish-and-tag.yml
--- a/.github/workflows/publish-and-tag.yml
+++ b/.github/workflows/publish-and-tag.yml
@@ -17,46 +17,43 @@ jobs:
       uses: actions/checkout@main
 
     - name: Install Miniconda
-      working-directory: ${{ github.workspace }}/../
-      run: |
-        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
-        bash Miniconda3-latest-Linux-x86_64.sh -b -p miniconda/
-        source miniconda/etc/profile.d/conda.sh
-        conda update -n base -c defaults conda -y
+      uses: conda-incubator/setup-miniconda@main
+      with:
+        channels: conda-forge
+        channel-priority: strict
+        miniconda-version: "latest"
+        auto-update-conda: true
+        auto-activate-base: true
+        activate-environment: scipion3
+        python-version: "3.12"
     
     - name: Install Scipion
       working-directory: ${{ github.workspace }}/../
       run: |
-        eval "$(miniconda/bin/conda shell.bash hook)"
         pip3 install --user scipion-installer
         python3 -m scipioninstaller -conda -noXmipp -noAsk scipion
 
     - name: Install Python dependencies
       run: |
-        python -m pip install --upgrade pip
         pip install setuptools wheel twine Pillow
         pip install -r requirements.txt
-    
-    - name: Build and publish
-      env:
-        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
-        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
-      run: |
-        eval "$(../miniconda/bin/conda shell.bash hook)"
-        conda activate scipion3
-        python setup.py sdist bdist_wheel
-        twine upload dist/* -c "{{ secrets.PYPI_COMMENT }}"
     
     - name: Get tag name
       id: variables
       env:
         FOLDER_WITH_VERSION: ${{ vars.FOLDER_WITH_VERSION }}
       run: |
-        eval "$(../miniconda/bin/conda shell.bash hook)"
-        conda activate scipion3
-        VERSION=$(python -c "import $FOLDER_WITH_VERSION; print('VERSION', 'v'+$FOLDER_WITH_VERSION.__version__)" | grep VERSION | sed "s/VERSION //g")
-        echo "RELEASE_NAME=$VERSION" >> $GITHUB_OUTPUT
+        VERSION=$(python -c "import $FOLDER_WITH_VERSION; print('VERSION', 'v'+$FOLDER_WITH_VERSION.__version__)" | grep VERSION | sed "s/VERSION //g") || (echo "Could not import version, check that variables are correctly set!" && exit 1)
         echo "TAG_NAME=${VERSION#v}" >> $GITHUB_OUTPUT
+        echo "TAG NAME (must not contain version prefix): ${VERSION#v}"
+    
+    - name: Build and publish
+      env:
+        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
+        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
+      run: |
+        python setup.py sdist bdist_wheel
+        twine upload dist/* -c "{{ secrets.PYPI_COMMENT }}"
     
     - name: Generate tag
       id: tag_version
